export const data = [
  {
    "id": 1,
    "country": "USA",
    "name": "Software Developer",
    "type": "Programming",
    "salary": "10,000 - 15,000",
    "location": "Remote",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "2 years",
    "description": "Developing web and mobile applications"
  },
  {
    "id": 2,
    "country": "Canada",
    "name": "Frontend Developer",
    "type": "Programming",
    "salary": "8,000 - 12,000",
    "location": "Toronto",
    "time": "Part-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "1 year",
    "description": "Building and maintaining web user interfaces"
  },
  {
    "id": 3,
    "country": "Germany",
    "name": "Backend Developer",
    "type": "Programming",
    "salary": "9,000 - 14,000",
    "location": "Berlin",
    "time": "Full-time",
    "status": "closed",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "3 years",
    "description": "Developing server-side logic and APIs"
  },
  {
    "id": 4,
    "country": "UK",
    "name": "Full Stack Developer",
    "type": "Programming",
    "salary": "11,000 - 16,000",
    "location": "London",
    "time": "Contract",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "4 years",
    "description": "Working on both frontend and backend systems"
  },
  {
    "id": 5,
    "country": "India",
    "name": "Mobile App Developer",
    "type": "Programming",
    "salary": "6,000 - 10,000",
    "location": "Remote",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "2 years",
    "description": "Building Android and iOS applications"
  },
  {
    "id": 6,
    "country": "Australia",
    "name": "DevOps Engineer",
    "type": "Programming",
    "salary": "10,000 - 13,000",
    "location": "Sydney",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "3 years",
    "description": "Automating software development pipelines"
  },
  {
    "id": 7,
    "country": "Japan",
    "name": "Game Developer",
    "type": "Programming",
    "salary": "9,000 - 14,000",
    "location": "Tokyo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "3 years",
    "description": "Designing and developing video games"
  },
  {
    "id": 8,
    "country": "Brazil",
    "name": "Data Scientist",
    "type": "Programming",
    "salary": "11,000 - 18,000",
    "location": "Sao Paulo",
    "time": "Part-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "5 years",
    "description": "Analyzing and interpreting complex data"
  },
  {
    "id": 9,
    "country": "France",
    "name": "AI Engineer",
    "type": "Programming",
    "salary": "12,000 - 20,000",
    "location": "Paris",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "4 years",
    "description": "Developing AI models and systems"
  },
  {
    "id": 10,
    "country": "South Africa",
    "name": "Cybersecurity Specialist",
    "type": "Programming",
    "salary": "9,000 - 14,000",
    "location": "Cape Town",
    "time": "Contract",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "3 years",
    "description": "Securing systems against cyber threats"
  },
  {
    "id": 11,
    "country": "USA",
    "name": "Automotive Engineer",
    "type": "Automotive Jobs",
    "salary": "7,000 - 10,000",
    "location": "Detroit",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "3 years",
    "description": "Designing and developing automotive systems"
  },
  {
    "id": 12,
    "country": "Germany",
    "name": "Car Mechanic",
    "type": "Automotive Jobs",
    "salary": "4,000 - 6,000",
    "location": "Berlin",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "5 years",
    "description": "Repairing and maintaining vehicles"
  },
  {
    "id": 13,
    "country": "UK",
    "name": "Auto Body Technician",
    "type": "Automotive Jobs",
    "salary": "5,000 - 7,000",
    "location": "London",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "4 years",
    "description": "Repairing and restoring vehicle bodies"
  },
  {
    "id": 14,
    "country": "Japan",
    "name": "Automotive Designer",
    "type": "Automotive Jobs",
    "salary": "8,000 - 12,000",
    "location": "Tokyo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "5 years",
    "description": "Designing aesthetic and functional aspects of vehicles"
  },
  {
    "id": 15,
    "country": "Italy",
    "name": "Quality Control Inspector",
    "type": "Automotive Jobs",
    "salary": "6,000 - 9,000",
    "location": "Milan",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "3 years",
    "description": "Inspecting vehicle parts and systems for quality assurance"
  },
  {
    "id": 16,
    "country": "France",
    "name": "Automotive Electrician",
    "type": "Automotive Jobs",
    "salary": "5,000 - 7,000",
    "location": "Paris",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "4 years",
    "description": "Installing and repairing electrical systems in vehicles"
  },
  {
    "id": 17,
    "country": "Canada",
    "name": "Service Advisor",
    "type": "Automotive Jobs",
    "salary": "4,000 - 6,000",
    "location": "Toronto",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "2 years",
    "description": "Advising customers on vehicle service and repairs"
  },
  {
    "id": 18,
    "country": "Australia",
    "name": "Automotive Painter",
    "type": "Automotive Jobs",
    "salary": "5,000 - 8,000",
    "location": "Sydney",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "4 years",
    "description": "Painting and finishing vehicles after repairs or customizations"
  },
  {
    "id": 19,
    "country": "Brazil",
    "name": "Production Line Worker",
    "type": "Automotive Jobs",
    "salary": "3,500 - 5,000",
    "location": "Sao Paulo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "2 years",
    "description": "Assembling parts on the automotive production line"
  },
  {
    "id": 20,
    "country": "South Korea",
    "name": "Vehicle Test Driver",
    "type": "Automotive Jobs",
    "salary": "6,000 - 9,000",
    "location": "Seoul",
    "time": "Contract",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "3 years",
    "description": "Testing vehicles for performance, safety, and reliability"
  },
  {
    "id": 21,
    "country": "USA",
    "name": "Registered Nurse",
    "type": "Health and Care",
    "salary": "6,000 - 9,000",
    "location": "New York",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "2 years",
    "description": "Providing patient care and medical support"
  },
  {
    "id": 22,
    "country": "UK",
    "name": "General Practitioner",
    "type": "Health and Care",
    "salary": "10,000 - 14,000",
    "location": "London",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "5 years",
    "description": "Diagnosing and treating common illnesses"
  },
  {
    "id": 23,
    "country": "Canada",
    "name": "Physiotherapist",
    "type": "Health and Care",
    "salary": "5,000 - 8,000",
    "location": "Toronto",
    "time": "Part-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "3 years",
    "description": "Rehabilitating patients with physical injuries"
  },
  {
    "id": 24,
    "country": "Australia",
    "name": "Pharmacist",
    "type": "Health and Care",
    "salary": "7,000 - 10,000",
    "location": "Sydney",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "4 years",
    "description": "Dispensing medication and providing health advice"
  },
  {
    "id": 25,
    "country": "Germany",
    "name": "Dentist",
    "type": "Health and Care",
    "salary": "12,000 - 18,000",
    "location": "Berlin",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "5 years",
    "description": "Providing oral health care and dental treatments"
  },
  {
    "id": 26,
    "country": "India",
    "name": "Medical Laboratory Technician",
    "type": "Health and Care",
    "salary": "3,500 - 6,000",
    "location": "Mumbai",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "2 years",
    "description": "Performing laboratory tests and analyzing samples"
  },
  {
    "id": 27,
    "country": "France",
    "name": "Pediatrician",
    "type": "Health and Care",
    "salary": "9,000 - 13,000",
    "location": "Paris",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "4 years",
    "description": "Providing medical care for infants and children"
  },
  {
    "id": 28,
    "country": "Brazil",
    "name": "Occupational Therapist",
    "type": "Health and Care",
    "salary": "6,000 - 9,000",
    "location": "Sao Paulo",
    "time": "Part-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "3 years",
    "description": "Helping patients regain daily living and working skills"
  },
  {
    "id": 29,
    "country": "South Africa",
    "name": "Mental Health Counselor",
    "type": "Health and Care",
    "salary": "5,000 - 7,000",
    "location": "Cape Town",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "3 years",
    "description": "Providing therapy and counseling for mental health issues"
  },
  {
    "id": 30,
    "country": "Japan",
    "name": "Surgeon",
    "type": "Health and Care",
    "salary": "15,000 - 25,000",
    "location": "Tokyo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "7 years",
    "description": "Performing surgical procedures to treat medical conditions"
  },
  {
    "id": 31,
    "country": "USA",
    "name": "Digital Marketing Manager",
    "type": "Marketing",
    "salary": "8,000 - 12,000",
    "location": "New York",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "3 years",
    "description": "Managing online marketing campaigns and strategies"
  },
  {
    "id": 32,
    "country": "UK",
    "name": "Content Marketing Specialist",
     "type": "Marketing",
    "salary": "5,000 - 7,000",
    "location": "London",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "2 years",
    "description": "Creating and distributing valuable content for marketing"
  },
  {
    "id": 33,
    "country": "Canada",
    "name": "SEO Specialist",
     "type": "Marketing",
    "salary": "4,500 - 6,500",
    "location": "Toronto",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "3 years",
    "description": "Optimizing websites to rank higher in search engines"
  },
  {
    "id": 34,
    "country": "Australia",
    "name": "Social Media Manager",
     "type": "Marketing",
    "salary": "5,000 - 8,000",
    "location": "Sydney",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "4 years",
    "description": "Managing social media platforms and engagement strategies"
  },
  {
    "id": 35,
    "country": "Germany",
    "name": "Marketing Analyst",
     "type": "Marketing",
    "salary": "6,000 - 9,000",
    "location": "Berlin",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "3 years",
    "description": "Analyzing data to improve marketing strategies"
  },
  {
    "id": 36,
    "country": "France",
    "name": "Brand Manager",
     "type": "Marketing",
    "salary": "7,000 - 10,000",
    "location": "Paris",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "5 years",
    "description": "Developing and maintaining a brand’s image and reputation"
  },
  {
    "id": 37,
    "country": "India",
    "name": "PPC Specialist",
     "type": "Marketing",
    "salary": "4,000 - 6,000",
    "location": "Mumbai",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "2 years",
    "description": "Managing pay-per-click advertising campaigns"
  },
  {
    "id": 38,
    "country": "Brazil",
    "name": "Email Marketing Manager",
     "type": "Marketing",
    "salary": "5,000 - 7,500",
    "location": "Sao Paulo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "3 years",
    "description": "Creating and managing email marketing campaigns"
  },
  {
    "id": 39,
    "country": "South Korea",
    "name": "Marketing Coordinator",
     "type": "Marketing",
    "salary": "3,500 - 5,500",
    "location": "Seoul",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "2 years",
    "description": "Coordinating marketing activities and event planning"
  },
  {
    "id": 40,
    "country": "Japan",
    "name": "Influencer Marketing Manager",
     "type": "Marketing",
    "salary": "6,000 - 9,000",
    "location": "Tokyo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "4 years",
    "description": "Building relationships with influencers for brand promotion"
  },
  {
    "id": 41,
    "country": "USA",
    "name": "Project Manager",
     "type": "Project Management",
    "salary": "9,000 - 13,000",
    "location": "Remote",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "5 years",
    "description": "Managing project timelines, scope, and resources"
  },
  {
    "id": 42,
    "country": "UK",
    "name": "Agile Project Manager",
    "type": "Project Management",
    "salary": "10,000 - 14,000",
    "location": "London",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "4 years",
    "description": "Leading Agile teams and managing sprints"
  },
  {
    "id": 43,
    "country": "Germany",
    "name": "Construction Project Manager",
    "type": "Project Management",
    "salary": "11,000 - 15,000",
    "location": "Berlin",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "6 years",
    "description": "Overseeing construction projects from planning to completion"
  },
  {
    "id": 44,
    "country": "Canada",
    "name": "IT Project Manager",
    "type": "Project Management",
    "salary": "8,000 - 12,000",
    "location": "Toronto",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "4 years",
    "description": "Managing IT infrastructure and software development projects"
  },
  {
    "id": 45,
    "country": "Australia",
    "name": "Marketing Project Manager",
    "type": "Project Management",
    "salary": "7,500 - 10,500",
    "location": "Sydney",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "3 years",
    "description": "Managing marketing campaigns and projects from start to finish"
  },
  {
    "id": 46,
    "country": "France",
    "name": "Healthcare Project Manager",
    "type": "Project Management",
    "salary": "8,000 - 11,000",
    "location": "Paris",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "5 years",
    "description": "Managing healthcare initiatives and hospital projects"
  },
  {
    "id": 47,
    "country": "India",
    "name": "Technical Project Manager",
    "type": "Project Management",
    "salary": "7,000 - 10,000",
    "location": "Bangalore",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "4 years",
    "description": "Managing technical projects in engineering and software development"
  },
  {
    "id": 48,
    "country": "Brazil",
    "name": "Product Launch Manager",
    "type": "Project Management",
    "salary": "6,500 - 9,500",
    "location": "Rio de Janeiro",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "3 years",
    "description": "Planning and managing product launches in different markets"
  },
  {
    "id": 49,
    "country": "Japan",
    "name": "Construction Site Manager",
    "type": "Project Management",
    "salary": "12,000 - 18,000",
    "location": "Tokyo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "6 years",
    "description": "Managing on-site construction activities and labor"
  },
  {
    "id": 50,
    "country": "South Korea",
    "name": "ERP Project Manager",
    "type": "Project Management",
    "salary": "9,000 - 13,000",
    "location": "Seoul",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "5 years",
    "description": "Managing enterprise resource planning (ERP) implementation projects"
  },
  {
    "id": 51,
    "country": "USA",
    "name": "Customer Service Representative",
    "type": "Customer Services",
    "salary": "3,000 - 5,000",
    "location": "Remote",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "1 year",
    "description": "Assisting customers with inquiries and resolving issues"
  },
  {
    "id": 52,
    "country": "UK",
    "name": "Call Center Agent",
    "type": "Customer Services",
    "salary": "2,500 - 4,000",
    "location": "London",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "1 year",
    "description": "Handling inbound and outbound customer calls"
  },
  {
    "id": 53,
    "country": "Canada",
    "name": "Customer Support Specialist",
    "type": "Customer Services",
    "salary": "4,000 - 6,000",
    "location": "Toronto",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "2 years",
    "description": "Providing technical support and troubleshooting for customers"
  },
  {
    "id": 54,
    "country": "Australia",
    "name": "Customer Care Coordinator",
    "type": "Customer Services",
    "salary": "3,500 - 5,500",
    "location": "Sydney",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "2 years",
    "description": "Coordinating customer service processes and managing cases"
  },
  {
    "id": 55,
    "country": "Germany",
    "name": "Help Desk Support",
    "type": "Customer Services",
    "salary": "3,000 - 4,500",
    "location": "Berlin",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/kXMX6GBN/c4.png",
    "experience": "1 year",
    "description": "Providing help desk support for technical issues"
  },
  {
    "id": 56,
    "country": "France",
    "name": "Customer Experience Manager",
    "type": "Customer Services",
    "salary": "5,000 - 7,000",
    "location": "Paris",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/TYk2rxDz/c5.png",
    "experience": "4 years",
    "description": "Managing and improving overall customer experience"
  },
  {
    "id": 57,
    "country": "India",
    "name": "Technical Support Representative",
    "type": "Customer Services",
    "salary": "2,500 - 4,000",
    "location": "Mumbai",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/qvzJwFcz/c6.png",
    "experience": "1 year",
    "description": "Providing technical support to customers over the phone and email"
  },
  {
    "id": 58,
    "country": "Brazil",
    "name": "Customer Service Team Lead",
    "type": "Customer Services",
    "salary": "4,000 - 6,000",
    "location": "Sao Paulo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/0Qp2mJYn/c1.png",
    "experience": "3 years",
    "description": "Leading a team of customer service representatives"
  },
  {
    "id": 59,
    "country": "Japan",
    "name": "Online Chat Support Agent",
    "type": "Customer Services",
    "salary": "3,000 - 5,000",
    "location": "Tokyo",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/59S22LNN/c3.png",
    "experience": "2 years",
    "description": "Providing support via online chat for customer inquiries"
  },
  {
    "id": 60,
    "country": "South Korea",
    "name": "Customer Relations Specialist",
    "type": "Customer Services",
    "salary": "4,000 - 6,500",
    "location": "Seoul",
    "time": "Full-time",
    "status": "open",
    "img": "https://i.postimg.cc/sxmjHd0Z/c2.png",
    "experience": "3 years",
    "description": "Managing customer relationships and resolving escalated issues"
  }
]
